import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Project, Report, AppSettings, ModelProvider } from '@/types';

// 内置提供商的固定 id
export const BUILTIN_GLM_ID = 'glm';
export const BUILTIN_MINIMAX_ID = 'minimax';

const GLM_BASE_URL = 'https://open.bigmodel.cn/api/paas/v4';
const MINIMAX_BASE_URL = 'https://api.minimax.io/v1';

function defaultProviders(): ModelProvider[] {
  return [
    { id: BUILTIN_GLM_ID, name: '智谱 GLM', protocol: 'glm', apiKey: '', model: 'glm-4.7-flash', baseUrl: GLM_BASE_URL, builtin: true },
    { id: BUILTIN_MINIMAX_ID, name: 'MiniMax', protocol: 'minimax', apiKey: '', model: 'MiniMax-M2.7', baseUrl: MINIMAX_BASE_URL, builtin: true },
  ];
}

// 把旧版扁平字段(aiProvider/glm*/minimax*)迁移成 providers 列表
function migrateSettings(raw: any): Partial<AppSettings> {
  if (!raw || typeof raw !== 'object') return {};
  if (Array.isArray(raw.providers) && raw.providers.length > 0) return raw; // 已是新结构

  const providers = defaultProviders();
  providers[0].apiKey = raw.glmApiKey ?? '';
  providers[0].model = raw.glmModel || 'glm-4.7-flash';
  providers[1].apiKey = raw.minimaxApiKey ?? '';
  providers[1].model = raw.minimaxModel || 'MiniMax-M2.7';
  providers[1].baseUrl = raw.minimaxBaseUrl || MINIMAX_BASE_URL;

  const { aiProvider, glmApiKey, glmModel, minimaxApiKey, minimaxModel, minimaxBaseUrl, ...rest } = raw;
  return {
    ...rest,
    providers,
    activeProviderId: aiProvider === 'minimax' ? BUILTIN_MINIMAX_ID : BUILTIN_GLM_ID,
  };
}

interface AppState {
  // Projects
  projects: Project[];
  addProject: (path: string) => void;
  updateProject: (id: string, data: Partial<Project>) => void;
  removeProject: (id: string) => void;

  // Settings
  settings: AppSettings;
  updateSettings: (settings: Partial<AppSettings>) => void;

  // Reports
  reports: Report[];
  addReport: (report: Report) => void;
  deleteReport: (id: string) => void;
}

const DEFAULT_PROMPT = `你是一个专业的周报助手。请根据我提供的 Git 提交记录，为我生成一份结构清晰、重点突出的周报。

**核心要求：**
1. **按项目严格分类**：提交记录中可能包含多个项目（以 \`[项目名]\` 标识）。请将“详细工作内容”部分按不同项目分开叙述，**不要**将所有内容混在一起。
2. **使用统一格式**：请严格按照以下提供的模板结构进行生成，确保格式统一、易于阅读。

**周报格式模板：**
---
**周报周期：** [自动计算起始日期] - [自动计算结束日期]

**详细工作内容：**

**【项目A名称】**
*   **功能/模块A1：** 描述相关提交完成的工作。
*   **功能/模块A2：** 描述相关提交完成的工作。
*   **优化与修复：** 描述相关的Bug修复、代码优化或重构工作。

**【项目B名称】**
*   **功能/模块B1：** 描述相关提交完成的工作。
*   **功能/模块B2：** 描述相关提交完成的工作。
*   **优化与修复：** 描述相关的Bug修复、代码优化或重构工作。

*(如果还有更多项目，请按相同格式添加)*
---

**请根据以下 Git 提交记录生成周报：**
{{commits}}`;

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      projects: [],
      settings: {
        authorName: '',
        providers: defaultProviders(),
        activeProviderId: BUILTIN_GLM_ID,
        promptTemplate: DEFAULT_PROMPT,
        autoGenerate: false,
        autoGenerateDay: 5, // Friday
        autoGenerateTime: '17:00',
        theme: 'dark', // 默认深色主题
        notionAutoSync: false,
        notionApiKey: '',
        notionParentPageId: '',
        notionProxyUrl: '',
        notionSyncMode: 'append',
        notionContentMode: 'markdown',
        updaterProxyUrl: '',
      },
      reports: [],

      addProject: (path) => {
        const { projects } = get();
        if (projects.some((p) => p.path === path)) {
          throw new Error('项目已存在');
        }

        const name = path.split(/[\\/]/).pop() || 'Unknown';
        set((state) => ({
          projects: [
            ...state.projects,
            {
              id: crypto.randomUUID(),
              path,
              name,
              lastUpdated: Date.now(),
              branchMode: 'all',
              authorMode: 'inherit',
            },
          ],
        }));
      },
      updateProject: (id: string, data: Partial<Project>) =>
        set((state) => ({
          projects: state.projects.map((p) =>
            p.id === id ? { ...p, ...data } : p
          ),
        })),
      removeProject: (id) =>
        set((state) => ({
          projects: state.projects.filter((p) => p.id !== id),
        })),

      updateSettings: (newSettings) =>
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        })),

      addReport: (report) =>
        set((state) => ({
          reports: [report, ...state.reports],
        })),
      deleteReport: (id) =>
        set((state) => ({
          reports: state.reports.filter((r) => r.id !== id),
        })),
    }),
    {
      name: 'git-weekly-reporter-storage',
      merge: (persistedState, currentState) => {
        const persisted = persistedState as Partial<AppState> | undefined;
        return {
          ...currentState,
          ...persisted,
          settings: {
            ...currentState.settings,
            ...migrateSettings(persisted?.settings),
          },
        };
      },
    }
  )
);
