import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Project, Report, AppSettings, ModelProvider } from '@/types';
import {
  CUSTOM_TEMPLATE_ID,
  DEFAULT_PROMPT,
  DEFAULT_TEMPLATE_ID,
  findTemplateByContent,
  findTemplateById,
  isLegacyPrompt,
} from './prompt-templates';

export { DEFAULT_PROMPT };
export { PROMPT_TEMPLATES, CUSTOM_TEMPLATE_ID, DEFAULT_TEMPLATE_ID } from './prompt-templates';
export type { PromptTemplate } from './prompt-templates';

// 内置提供商的固定 id
export const BUILTIN_GLM_ID = 'glm';
export const BUILTIN_MINIMAX_ID = 'minimax';

const GLM_BASE_URL = 'https://open.bigmodel.cn/api/paas/v4';
const MINIMAX_BASE_URL = 'https://api.minimax.io/v1';

function defaultProviders(): ModelProvider[] {
  return [
    { id: BUILTIN_GLM_ID, name: '智谱 GLM', protocol: 'glm', apiKey: '', model: 'glm-4.7-flash', baseUrl: GLM_BASE_URL, builtin: true },
    { id: BUILTIN_MINIMAX_ID, name: 'MiniMax', protocol: 'minimax', apiKey: '', model: 'MiniMax-M2.7', baseUrl: MINIMAX_BASE_URL, builtin: true },
  ];
}

// 确定当前该用哪个提示词。用的是内置模板就跟随代码更新（否则持久化会把旧
// 提示词永久固定住，改模板对老用户完全无效）；用户自己改过的一律原样保留。
function resolvePromptTemplate(raw: any): any {
  const content = typeof raw?.promptTemplate === 'string' ? raw.promptTemplate : '';
  let id: string | undefined = raw?.promptTemplateId;

  if (!id) {
    // 老数据没存 id：内容只要是任一内置模板或开发期的中间版本，就说明用户
    // 从没自己改过，升级到最新默认。注意不能反查成那个旧模板的 id——那会把
    // 老用户永久钉死在最早的模板上，再也拿不到新默认。
    // 主动选过模板的人存了 id，走下面的分支，不受这里影响。
    const untouched = !content || isLegacyPrompt(content) || !!findTemplateByContent(content);
    id = untouched ? DEFAULT_TEMPLATE_ID : CUSTOM_TEMPLATE_ID;
  }

  if (id === CUSTOM_TEMPLATE_ID) {
    return { ...raw, promptTemplateId: CUSTOM_TEMPLATE_ID };
  }

  const template = findTemplateById(id) ?? findTemplateById(DEFAULT_TEMPLATE_ID)!;
  return { ...raw, promptTemplateId: template.id, promptTemplate: template.content };
}

// 把旧版扁平字段(aiProvider/glm*/minimax*)迁移成 providers 列表
function migrateSettings(input: any): Partial<AppSettings> {
  if (!input || typeof input !== 'object') return {};
  const raw = resolvePromptTemplate(input);
  if (Array.isArray(raw.providers) && raw.providers.length > 0) return raw; // 已是新结构

  const providers = defaultProviders();
  providers[0].apiKey = raw.glmApiKey ?? '';
  providers[0].model = raw.glmModel || 'glm-4.7-flash';
  providers[1].apiKey = raw.minimaxApiKey ?? '';
  providers[1].model = raw.minimaxModel || 'MiniMax-M2.7';
  providers[1].baseUrl = raw.minimaxBaseUrl || MINIMAX_BASE_URL;

  const { aiProvider, glmApiKey, glmModel, minimaxApiKey, minimaxModel, minimaxBaseUrl, ...rest } = raw;
  return {
    ...rest,
    providers,
    activeProviderId: aiProvider === 'minimax' ? BUILTIN_MINIMAX_ID : BUILTIN_GLM_ID,
  };
}

interface AppState {
  // Projects
  projects: Project[];
  addProject: (path: string) => void;
  updateProject: (id: string, data: Partial<Project>) => void;
  removeProject: (id: string) => void;

  // Settings
  settings: AppSettings;
  updateSettings: (settings: Partial<AppSettings>) => void;

  // Reports
  reports: Report[];
  addReport: (report: Report) => void;
  deleteReport: (id: string) => void;
}


export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      projects: [],
      settings: {
        authorName: '',
        providers: defaultProviders(),
        activeProviderId: BUILTIN_GLM_ID,
        promptTemplate: DEFAULT_PROMPT,
        promptTemplateId: DEFAULT_TEMPLATE_ID,
        autoGenerate: false,
        autoGenerateDay: 5, // Friday
        autoGenerateTime: '17:00',
        theme: 'dark', // 默认深色主题
        notionAutoSync: false,
        notionApiKey: '',
        notionParentPageId: '',
        notionProxyUrl: '',
        notionSyncMode: 'append',
        notionContentMode: 'markdown',
        updaterProxyUrl: '',
      },
      reports: [],

      addProject: (path) => {
        const { projects } = get();
        if (projects.some((p) => p.path === path)) {
          throw new Error('项目已存在');
        }

        const name = path.split(/[\\/]/).pop() || 'Unknown';
        set((state) => ({
          projects: [
            ...state.projects,
            {
              id: crypto.randomUUID(),
              path,
              name,
              lastUpdated: Date.now(),
              branchMode: 'all',
              authorMode: 'inherit',
            },
          ],
        }));
      },
      updateProject: (id: string, data: Partial<Project>) =>
        set((state) => ({
          projects: state.projects.map((p) =>
            p.id === id ? { ...p, ...data } : p
          ),
        })),
      removeProject: (id) =>
        set((state) => ({
          projects: state.projects.filter((p) => p.id !== id),
        })),

      updateSettings: (newSettings) =>
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        })),

      addReport: (report) =>
        set((state) => ({
          reports: [report, ...state.reports],
        })),
      deleteReport: (id) =>
        set((state) => ({
          reports: state.reports.filter((r) => r.id !== id),
        })),
    }),
    {
      name: 'git-weekly-reporter-storage',
      merge: (persistedState, currentState) => {
        const persisted = persistedState as Partial<AppState> | undefined;
        return {
          ...currentState,
          ...persisted,
          settings: {
            ...currentState.settings,
            ...migrateSettings(persisted?.settings),
          },
        };
      },
    }
  )
);
