import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Project, Report, AppSettings, ModelProvider } from '@/types';

// 内置提供商的固定 id
export const BUILTIN_GLM_ID = 'glm';
export const BUILTIN_MINIMAX_ID = 'minimax';

const GLM_BASE_URL = 'https://open.bigmodel.cn/api/paas/v4';
const MINIMAX_BASE_URL = 'https://api.minimax.io/v1';

function defaultProviders(): ModelProvider[] {
  return [
    { id: BUILTIN_GLM_ID, name: '智谱 GLM', protocol: 'glm', apiKey: '', model: 'glm-4.7-flash', baseUrl: GLM_BASE_URL, builtin: true },
    { id: BUILTIN_MINIMAX_ID, name: 'MiniMax', protocol: 'minimax', apiKey: '', model: 'MiniMax-M2.7', baseUrl: MINIMAX_BASE_URL, builtin: true },
  ];
}

// 把旧版扁平字段(aiProvider/glm*/minimax*)迁移成 providers 列表
function migrateSettings(raw: any): Partial<AppSettings> {
  if (!raw || typeof raw !== 'object') return {};
  if (Array.isArray(raw.providers) && raw.providers.length > 0) return raw; // 已是新结构

  const providers = defaultProviders();
  providers[0].apiKey = raw.glmApiKey ?? '';
  providers[0].model = raw.glmModel || 'glm-4.7-flash';
  providers[1].apiKey = raw.minimaxApiKey ?? '';
  providers[1].model = raw.minimaxModel || 'MiniMax-M2.7';
  providers[1].baseUrl = raw.minimaxBaseUrl || MINIMAX_BASE_URL;

  const { aiProvider, glmApiKey, glmModel, minimaxApiKey, minimaxModel, minimaxBaseUrl, ...rest } = raw;
  return {
    ...rest,
    providers,
    activeProviderId: aiProvider === 'minimax' ? BUILTIN_MINIMAX_ID : BUILTIN_GLM_ID,
  };
}

interface AppState {
  // Projects
  projects: Project[];
  addProject: (path: string) => void;
  updateProject: (id: string, data: Partial<Project>) => void;
  removeProject: (id: string) => void;

  // Settings
  settings: AppSettings;
  updateSettings: (settings: Partial<AppSettings>) => void;

  // Reports
  reports: Report[];
  addReport: (report: Report) => void;
  deleteReport: (id: string) => void;
}

export const DEFAULT_PROMPT = `你是一位资深的技术负责人，擅长从琐碎的开发记录中提炼出真正有价值的工作成果。请根据我提供的 Git 提交记录，生成一份面向团队与上级、重点突出、易于阅读的周报。

**核心原则（务必严格遵守）：**
1. **归纳提炼，拒绝流水账**：绝对不要逐条翻译或罗列每一条 commit。请把围绕同一功能/目标的多条提交（多次开发、修复、优化）**合并归纳成一件完整的工作成果**，用一句话讲清楚“做了什么、达成了什么价值”，而不是“改动了哪些代码”。
2. **聚焦成果与价值**：从使用者或业务视角描述工作意义（解决了什么问题、带来了什么改进、完成了什么能力），而非机械复述技术细节或提交信息原文。
3. **过滤噪音**：忽略无实质意义的提交，例如版本号变更（bump version）、合并提交（merge）、代码格式调整、拼写修正、临时提交（wip）等，不要写进周报。
4. **控制篇幅、突出重点**：每个项目只保留 3~6 条最重要的工作，按重要性排序；零散的小改动请合并到“其他优化与修复”一条里概括，不要展开。
5. **按项目分类**：提交记录中可能包含多个项目（以 \`[项目名]\` 标识）。请按项目分开叙述，不要把不同项目的内容混在一起。

**周报格式模板：**
---
**详细工作内容：**

**【项目A名称】**
*   **核心工作一：** 一句话概括完成的成果及其价值（可由多条相关提交归纳而来）。
*   **核心工作二：** 一句话概括完成的成果及其价值。
*   **其他优化与修复：** 概括性描述本项目其余的 Bug 修复、重构与零散优化，无需逐条展开。

**【项目B名称】**
*   **核心工作一：** ……

*(如有更多项目，请按相同格式添加；若某项目本周提交很少，可精简为 1~2 条)*
---

**请根据以下 Git 提交记录生成周报（牢记：归纳成果，而非罗列提交）：**
{{commits}}`;

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      projects: [],
      settings: {
        authorName: '',
        providers: defaultProviders(),
        activeProviderId: BUILTIN_GLM_ID,
        promptTemplate: DEFAULT_PROMPT,
        autoGenerate: false,
        autoGenerateDay: 5, // Friday
        autoGenerateTime: '17:00',
        theme: 'dark', // 默认深色主题
        notionAutoSync: false,
        notionApiKey: '',
        notionParentPageId: '',
        notionProxyUrl: '',
        notionSyncMode: 'append',
        notionContentMode: 'markdown',
        updaterProxyUrl: '',
      },
      reports: [],

      addProject: (path) => {
        const { projects } = get();
        if (projects.some((p) => p.path === path)) {
          throw new Error('项目已存在');
        }

        const name = path.split(/[\\/]/).pop() || 'Unknown';
        set((state) => ({
          projects: [
            ...state.projects,
            {
              id: crypto.randomUUID(),
              path,
              name,
              lastUpdated: Date.now(),
              branchMode: 'all',
              authorMode: 'inherit',
            },
          ],
        }));
      },
      updateProject: (id: string, data: Partial<Project>) =>
        set((state) => ({
          projects: state.projects.map((p) =>
            p.id === id ? { ...p, ...data } : p
          ),
        })),
      removeProject: (id) =>
        set((state) => ({
          projects: state.projects.filter((p) => p.id !== id),
        })),

      updateSettings: (newSettings) =>
        set((state) => ({
          settings: { ...state.settings, ...newSettings },
        })),

      addReport: (report) =>
        set((state) => ({
          reports: [report, ...state.reports],
        })),
      deleteReport: (id) =>
        set((state) => ({
          reports: state.reports.filter((r) => r.id !== id),
        })),
    }),
    {
      name: 'git-weekly-reporter-storage',
      merge: (persistedState, currentState) => {
        const persisted = persistedState as Partial<AppState> | undefined;
        return {
          ...currentState,
          ...persisted,
          settings: {
            ...currentState.settings,
            ...migrateSettings(persisted?.settings),
          },
        };
      },
    }
  )
);
