export interface Project {
  id: string;
  path: string;
  name: string;
  alias?: string;
  lastUpdated: number;
}

export interface CommitLog {
  hash: string;
  author: string;
  date: string;
  message: string;
  project: string;
  branch?: string;
}

export interface Report {
  id: string;
  createdAt: number;
  dateRange: {
    start: string;
    end: string;
  };
  content: string; // Markdown content
  status: 'draft' | 'generated' | 'failed';
  // Meta data for display
  projects?: string[]; // List of project names involved
  branches?: string[]; // List of branches involved
  totalCommits?: number;
}

export interface AppSettings {
  authorName: string;
  glmApiKey: string;
  promptTemplate: string;
  autoGenerate: boolean;
  autoGenerateDay: number; // 0-6 (Sunday-Saturday)
  autoGenerateTime: string; // "HH:mm"
  theme: 'light' | 'dark' | 'system'; // 主题设置
  notionAutoSync: boolean;
  notionApiKey: string;
  notionParentPageId: string;
  notionProxyUrl: string;
  notionSyncMode: 'append' | 'subpage';
  notionContentMode: 'markdown' | 'code';
}
