// 分支抓取范围：当前分支 / 全部分支 / 指定分支
export type BranchMode = 'current' | 'all' | 'specific';
// 作者过滤范围：继承全局 / 全部作者 / 指定作者
export type AuthorMode = 'inherit' | 'all' | 'specific';

export interface Project {
  id: string;
  path: string;
  name: string;
  alias?: string;
  lastUpdated: number;
  // 每项目抓取配置（缺省时按 'all' / 'inherit' 处理，见 git.ts）
  branchMode?: BranchMode;
  branch?: string; // branchMode === 'specific' 时生效
  authorMode?: AuthorMode;
  author?: string; // authorMode === 'specific' 时生效
}

export interface CommitLog {
  hash: string;
  author: string;
  date: string;
  message: string;
  project: string;
  branch?: string;
}

export interface Report {
  id: string;
  createdAt: number;
  dateRange: {
    start: string;
    end: string;
  };
  content: string; // Markdown content
  status: 'draft' | 'generated' | 'failed';
  // Meta data for display
  projects?: string[]; // List of project names involved
  branches?: string[]; // List of branches involved
  totalCommits?: number;
}

export type AiProvider = 'glm' | 'minimax';

export interface AppSettings {
  authorName: string;
  aiProvider: AiProvider;
  glmApiKey: string;
  glmModel: string;
  minimaxApiKey: string;
  minimaxModel: string;
  minimaxBaseUrl: string;
  promptTemplate: string;
  autoGenerate: boolean;
  autoGenerateDay: number; // 0-6 (Sunday-Saturday)
  autoGenerateTime: string; // "HH:mm"
  theme: 'light' | 'dark' | 'system'; // 主题设置
  notionAutoSync: boolean;
  notionApiKey: string;
  notionParentPageId: string;
  notionProxyUrl: string;
  notionSyncMode: 'append' | 'subpage';
  notionContentMode: 'markdown' | 'code';
}
